### ISSUE TITLE
[PROPOSAL] Renaming project?

### ISSUE THREAD

**Issue by twity1337** [RomuloOliveira/commit-messages-guide#50]
Thank you all for this nice guide! It's a good introduction for beginners to git.

Since it seems to become more a general git-guide than a "how to write good commit messages"-guide it may be better to rename the project.

It also may be better to reorganize some things, because the jump from "good commit message" to "rebase vs merge" was a bit confusing for me as a first-time reader. Maybe adding some kind of TOC or something...

What do you think about this proposal?

**Comment by RomuloOliveira** [comment]
Hey, @twity1337. I think a TOC would be great and would help people what they want to find faster (feel free to open an issue on that).

Even though there is a lot of more information about git and commits in general, I don't have any intention to turn this guide into a general purpose git guide. I think renaming the project would cause the project to be bad at being a general guide. This would require additional effort to be at a "good enough" state, which we may not achieve. That's why I think that keeping it focused in the commit messages (although not strictly restrict to it) it's better.
